model:
  model_name: Linear regression
  class_name: LinearRegression
  model_description: >
    См. https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html
  
  problem: regression

  train_metrics:
    - 'r2'
    - 'neg_mean_squared_error'
    - 'neg_mean_absolute_error'

  train_hyperparameters:
    - name: fit_intercept
      description: Whether to calculate the intercept for this model. If set to False, no intercept will be used in calculations (i.e. data is expected to be centered).
      type: bool
      default_value: True

